---
name: "Pull Request"
description: "Suggest code/documentation changes to this project."
title: "[PR] <brief description>"
labels: ["pull request"]
body:
  - type: markdown
    attributes:
      value: "Thank you for your contribution! Please fill out the details below."
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "What does this PR do?"
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: "Changes"
      description: "List the main changes in this PR."
    validations:
      required: true
  - type: textarea
    id: testing
    attributes:
      label: "Testing"
      description: "How did you test these changes?"
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: "Related Issues"
      description: "Link any related issues or discussions."
    validations:
      required: false
