name: "Feature request"
description: "Suggest an idea for this project."
title: "[FEATURE] <describe the feature>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "Thank you for your suggestion! Please fill out the details below."
  - type: input
    id: summary
    attributes:
      label: "Feature summary"
      description: "A clear and concise description of the feature you want."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature important to you?"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Have you considered any alternatives?"
    validations:
      required: false
